version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: avito_bot_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always

  redis:
    image: redis:7-alpine
    container_name: avito_bot_redis
    ports:
      - "6381:6379"
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: avito_bot_pgbouncer
    environment:
      # Как PgBouncer подключается к реальной базе на хосте
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@host.docker.internal:${DB_PORT}/${DB_NAME}
      
      # Настройки авторизации для самого PgBouncer (чтобы он пустил наше приложение)
      - AUTH_TYPE=md5
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      
      # Пул соединений
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - POOL_MODE=transaction
      - IGNORE_STARTUP_PARAMETERS=extra_float_digits
    ports:
      - "6432:6432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always