version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: avito_bot_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always

  redis:
    image: redis:7-alpine
    container_name: avito_bot_redis
    ports:
      - "6381:6379"
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: avito_bot_pgbouncer
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - LISTEN_PORT=6432
      # Используем именно этот тип, так как он работает в твоем окружении
      - AUTH_TYPE=scram-sha-256
      # Помогает избежать проблем с параметрами, которые шлет asyncpg
      - IGNORE_STARTUP_PARAMETERS=extra_float_digits,client_encoding
    ports:
      - "6434:6432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always